### ISSUE TITLE
request a license

### ISSUE THREAD

**Issue by songsammy** [svidgen/shooty-ship-13k#1]
For any open source project, license is a must. I'd like to use this project and I want to be sure that I am allowed to do so, like publishing a modified version.
You may refer to https://choosealicense.com/

**Comment by svidgen** [comment]
Sorry for the delay, @songsammy. I've adopted the MIT license for this. I would love it if you could link back to this repo and/or thepointless.com if you use or learn significantly from what I've done. But, it's certainly not required.

Happy coding!
